
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'sf_poc_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

#Variables
#Generic variables used in all models
vars:
  #Snowflake schema where are all the raw tables
  schema: "RAW_SCHEMA"
  #Snowflake user to grant privileges for each model
  snowflake_user_grant_privileges: "ACCOUNTADMIN"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  sf_poc_dbt:
      # Applies to all files under models/example/
    #materialized: ephemeral
    materialized: table
    m_territory:
        alias: m_territory        
    m_product:
        alias: m_product
    m_null_country_values:
        alias: m_null_country_values
    tmp_call_hierarchy:
        alias: tmp_call_hierarchy
    tmp_f_call:
        alias: tmp_f_call
    tmp_f_call_account:
        alias: tmp_f_call_account
    tmp_f_call_user:        
        alias: tmp_f_call_user
    tmp_call_hierarchy_1:
        alias: tmp_call_hierarchy_1
    tmp_call_hierarchy_2:
        alias: tmp_call_hierarchy_2
    tmp_call:
        alias: tmp_call    
    tmp_user_territory:
        alias: tmp_user_territory                
    f_survey_target:
        alias: f_survey_target                
    tmp_f_process_instance:
        alias: tmp_f_process_instance                
    f_event_approval_process:
        alias: f_event_approval_process        
    tmp_f_event_1:
        alias: tmp_f_event_1        
    tmp_f_event_2:
        alias: tmp_f_event_2        
    tmp_event_attendee:
        alias: tmp_event_attendee        
    tmp_f_event_detail_1:
        alias: tmp_f_event_detail_1        
    tmp_f_event_detail_2_3:
        alias: tmp_f_event_detail_2_3        
    tmp_anonymous_surveys:
        alias: tmp_anonymous_surveys        
    tmp_f_event_detail_4:
        alias: tmp_f_event_detail_4        
    tmp_yearly_ffs:
        alias: tmp_yearly_ffs        
    tmp_yearly_attendance:
        alias: tmp_yearly_attendance        
    tmp_yearly_attendance_main_kpi:
        alias: tmp_yearly_attendance_main_kpi
    tmp_f_campaign:
        alias: tmp_f_campaign
    f_survey_target_events:                        
        alias: f_survey_target_events
    f_eligible_event_attendee:
        alias: f_eligible_event_attendee
    f_process_instance_step:
        alias: f_process_instance_step
    f_call:
        alias: f_call        
    f_event:
        alias: f_event        
    f_event_detail:
        alias: f_event_detail
    f_campaign:
        alias: f_campaign