
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'sf_poc_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

#Variables
#Generic variables used in all models
vars:
  #Snowflake schema where are all the raw tables
  schema: "RAW_SCHEMA"
  #Snowflake user to grant privileges for each model
  snowflake_user_grant_privileges: "ACCOUNTADMIN"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  sf_poc_dbt:
      # Applies to all files under models/example/
    #materialized: ephemeral
    materialized: table
    m_territory:
        alias: m_territory        
    m_product:
        alias: m_product
    m_null_country_values:
        alias: m_null_country_values
    tmp_call_hierarchy:
        alias: tmp_call_hierarchy
    tmp_f_call:
        alias: tmp_f_call
    tmp_f_call_account:
        alias: tmp_f_call_account
    tmp_f_call_user:        
        alias: tmp_f_call_user
    tmp_call_hierarchy_1:
        alias: tmp_call_hierarchy_1
    tmp_call_hierarchy_2:
        alias: tmp_call_hierarchy_2
    tmp_call:
        alias: tmp_call    
    tmp_user_territory:
        alias: tmp_user_territory                
    f_survey_target:
        alias: f_survey_target                
    tmp_f_process_instance:
        alias: tmp_f_process_instance                
    f_event_approval_process:
        alias: f_event_approval_process        
    tmp_f_event_1:
        alias: tmp_f_event_1        
    tmp_f_event_2:
        alias: tmp_f_event_2        
    tmp_event_attendee:
        alias: tmp_event_attendee        
    tmp_f_event_detail_1:
        alias: tmp_f_event_detail_1        
    tmp_f_event_detail_2_3:
        alias: tmp_f_event_detail_2_3        
    tmp_anonymous_surveys:
        alias: tmp_anonymous_surveys        
    tmp_f_event_detail_4:
        alias: tmp_f_event_detail_4        
    tmp_yearly_ffs:
        alias: tmp_yearly_ffs        
    tmp_yearly_attendance:
        alias: tmp_yearly_attendance        
    tmp_yearly_attendance_main_kpi:
        alias: tmp_yearly_attendance_main_kpi
    tmp_f_campaign:
        alias: tmp_f_campaign
    tmp_f_activity_email_eloqua:
        alias: tmp_f_activity_email_eloqua
    f_survey_target_events:                        
        alias: f_survey_target_events
    f_eligible_event_attendee:
        alias: f_eligible_event_attendee
    f_process_instance_step:
        alias: f_process_instance_step
    f_call:
        alias: f_call        
    f_event:
        alias: f_event        
    f_event_detail:
        alias: f_event_detail
    f_campaign:
        alias: f_campaign    
    f_campaign_clickthrough_counter:
        alias: f_campaign_clickthrough_counter
    f_campaign_open_counter:
        alias: f_campaign_open_counter
    f_iconnect_campaign:
        alias: f_iconnect_campaign
    f_account_plan:
        alias: f_account_plan
    f_account_plan_actions:
        alias: f_account_plan_actions
    f_account_plan_activities_counter:
        alias: f_account_plan_activities_counter
    f_account_plan_counter:
        alias: f_account_plan_counter
    f_account_plan_objectives:
        alias: f_account_plan_objectives
    f_account_plan_objectives_counter:
        alias: f_account_plan_objectives_counter
    f_account_plan_profile:
        alias: f_account_plan_profile
    f_approved_email:
        alias: f_approved_email
    f_approved_email_counters:
        alias: f_approved_email_counters
    f_channel_recomendations:
        alias: f_channel_recomendations
    f_content_recomendations:
        alias: f_content_recomendations
    #f_customer_request:
    #    alias: f_customer_request
    f_cycle_plan:
        alias: f_cycle_plan
    f_key_message_link:
        alias: f_key_message_link
    f_knowledge_kav:
        alias: f_knowledge_kav
    f_livechat_transcript:
        alias: f_livechat_transcript
    f_mc_cycle_plan:
        alias: f_mc_cycle_plan
    f_multichannel_activity:
        alias: f_multichannel_activity
    f_my_insights_analytics:
        alias: f_my_insights_analytics
    tmp_f_one_to_one_email:
        alias: tmp_f_one_to_one_email
    f_one_to_one_email:
        alias: f_one_to_one_email
    f_question:
        alias: f_question
    f_question_response:
        alias: f_question_response
    f_survey:
        alias: f_survey
    f_survey_question:
        alias: f_survey_question
    tmp_f_time_effectiveness:
        alias: tmp_f_time_effectiveness
    f_time_effectiveness:
        alias: f_time_effectiveness
    f_time_effectiveness_employee:
        alias: f_time_effectiveness_employee
    f_time_registration:
        alias: f_time_registration
    m_account:
        alias: m_account
    m_account_plan_key_stakeholders:
        alias: m_account_plan_key_stakeholders
    m_account_plan_team_members:
        alias: m_account_plan_team_members
    m_activity:
        alias: m_activity
    m_affiliation:
        alias: m_affiliation
    m_assignment:
        alias: m_assignment
    m_campaign:
        alias: m_campaign
    m_channel_preference_completeness:
        alias: m_channel_preference_completeness
    m_case_history:
        alias: m_case_history
    m_channel_permission:
        alias: m_channel_permission
    m_clm_presentation:
        alias: m_clm_presentation
    m_cycle_plan:
        alias: m_cycle_plan
    m_dynamic_attribute:
        alias: m_dynamic_attribute
    m_dynamic_attribute_configuration:
        alias: m_dynamic_attribute_configuration
    m_employee:
        alias: m_employee
    m_focus_area:
        alias: m_focus_area