---Validates if medical call have product target class
SELECT DISTINCT PRODUCT_TARGET_CLASS
FROM "PRD_POC_DB"."BUSINESS_SCHEMA"."BUW_CALLS_CALLS_F_CALL" c LEFT JOIN "PRD_POC_DB"."BUSINESS_SCHEMA"."BUW_MARKETING_MARKET_SEGMENTATION_M_PRODUCT_METRICS_EMEA" pm
ON c.PRODUCT_ID = pm.PRODUCT_ID
WHERE CALL_RECORD_TYPE = 'Medical Call' AND len(PRODUCT_TARGET_CLASS)>0