{{ config(
	post_hook="grant all privileges on {{ this }} to {{ var('snowflake_user_grant_privileges') }}")
}}

select u.ALIAS as "Employee_Alias",
       u.CITY as "Employee_City", 
       u.COMMUNITYNICKNAME as "Employee_Nickname", 
       u.CURRENCYISOCODE as "Employee_Currency_Code",
       u.DIVISION as "Employee_Division", 
       u.EMAIL as "Employee_Email",
       u.FULLPHOTOURL as "Employee_Photo", 
       u.ID as "Employee_Id", 
       u.JJ_ACTIVE_CYCLE_PLAN__C as "Employee_Current_Cycle_Plan",
       u.JJ_PREVIOUS_CYCLE_PLAN__C as "Employee_Previous_Cycle_Plan", 
       CASE WHEN u.ISACTIVE=1 THEN 'yes' ELSE 'no' END as "Employee_Is_Active",
       u.JJ_USER_COUNTRY__C as "Employee_Country", 
       u.JJ_COE_USER__C as "Employee_COE_User", 
       u.COUNTRY_ISO_CODE as "Employee_Country_Code",
       case when UPPER(REPLACE(REPLACE(cs.JJ_REGION__C, ' ', ''), '/', '-')) = 'SOUTHERNAFRICA' then 'South Africa' else REPLACE(REPLACE(cs.JJ_REGION__C, ' ', ''), '/', '-') end as "Employee_Region", 
       u.JJ_USER_WWID__C as "Employee_WWID",
       u.MANAGERID as "Manager_Id", 
       u.NAME as "Employee", 
       u.PHONE as "Employee_Phone",
       u.PROFILEID as "Profile_Id",
       pr.NAME as "Employee_Department", 
       u.USERROLEID as "Role_Id",
       u.USERTYPE as "Employee_Type",
       u.USERNAME as "Employee_Username",
       UPPER(SUBSTRING(u.USERNAME, 0, CHARINDEX('@',u.USERNAME))) as "Employee_NTNAME",
       u.JJ_POSITION_TYPE__C as "Employee_Position_Type",
       u.JJ_GROUP_1__C as "Employee_Group_1", 
       u.JJ_GROUP_2__C as "Employee_Group_2",
       TO_CHAR(TO_DATE(u.CREATEDDATE, 'YYYYMMDD HH24:MI:SS'), 'DD-MM-YYYY') as "Employee_User_Creation_Date",
       CASE WHEN u.LASTLOGINDATE = '' THEN NULL ELSE TO_CHAR(TO_DATE(u.LASTLOGINDATE, 'YYYYMMDD HH24:MI:SS'), 'DD-MM-YYYY') END as "Employee_Last_Login_Date",
       u.JJ_FOCUS_PRODUCTS__C as "Employee_Focus_Products",
	   u.jj_products__c as employee_list_of_products,
	   u.state as employee_state,
	   u.department as employee_user_department,
	   u.postalcode as employee_zip_cd,
	   u.profile_name_vod__c as profile_type_txt,
	   case when u.profile_name_vod__c = 'EMEA_iConnect_Sales' and u.jj_position_type__c = 'Sales Rep' then 'true' else 'false' end as employee_is_salesrep,
	   u.jj_user_group__c as employee_user_group,
	   case when u.JJ_MSL_PRCT__C = '' then null else u.JJ_MSL_PRCT__C end as MSL_percentage
  from      {{ source('raw', 'user') }} u
  left join {{ source('raw', 'country_settings') }} cs
    on u.COUNTRY_ISO_CODE = cs.COUNTRY_ISO_CODE
  left join {{ source('raw', 'profile') }} pr
    on pr.ID = u.PROFILEID
 group by u.ALIAS,
          u.CITY, 
          u.COMMUNITYNICKNAME, 
          u.CURRENCYISOCODE,
          u.DIVISION, 
          u.EMAIL,
          u.FULLPHOTOURL, 
          u.ID, 
          u.JJ_ACTIVE_CYCLE_PLAN__C,
          u.JJ_PREVIOUS_CYCLE_PLAN__C, 
          CASE WHEN u.ISACTIVE=1 THEN 'yes' ELSE 'no' END,
          u.JJ_USER_COUNTRY__C, 
          u.JJ_COE_USER__C, 
          u.COUNTRY_ISO_CODE,
          case when UPPER(REPLACE(REPLACE(cs.JJ_REGION__C, ' ', ''), '/', '-')) = 'SOUTHERNAFRICA' then 'South Africa' else REPLACE(REPLACE(cs.JJ_REGION__C, ' ', ''), '/', '-') end, 
          u.JJ_USER_WWID__C,
          u.MANAGERID, 
          u.NAME, 
          u.PHONE,
          u.PROFILEID,
          pr.NAME, 
          u.USERROLEID,
          u.USERTYPE,
          u.USERNAME,
          UPPER(SUBSTRING(u.USERNAME, 0, CHARINDEX('@',u.USERNAME))),
          u.JJ_POSITION_TYPE__C,
          u.JJ_GROUP_1__C, 
          u.JJ_GROUP_2__C,
          TO_CHAR(TO_DATE(u.CREATEDDATE, 'YYYYMMDD HH24:MI:SS'), 'DD-MM-YYYY'),
          CASE WHEN u.LASTLOGINDATE = '' THEN NULL ELSE TO_CHAR(TO_DATE(u.LASTLOGINDATE, 'YYYYMMDD HH24:MI:SS'), 'DD-MM-YYYY') END,
          u.JJ_FOCUS_PRODUCTS__C,
		  u.jj_products__c,
	      u.state,
	      u.department,
	      u.postalcode,
	      u.profile_name_vod__c,
	      case when u.profile_name_vod__c = 'EMEA_iConnect_Sales' and u.jj_position_type__c = 'Sales Rep' then 'true' else 'false' end,
	      u.jj_user_group__c,
		  case when u.JJ_MSL_PRCT__C = '' then null else u.JJ_MSL_PRCT__C end
