{{ config(
	post_hook="grant all privileges on {{ this }} to {{ var('snowflake_user_grant_privileges') }}")
}}

SELECT 
	ID
	,CURRENCYISOCODE
	,CREATEDDATE
	,CREATEDBYID
	,LASTMODIFIEDDATE
	,LASTMODIFIEDBYID
	,JJ_ACCOUNT__C
	,JJ_ACADEMIA_VALUE__C
	,JJ_ACADEMIA__C
	,JJ_BOARD_MEMBER_VALUE__C
	,JJ_BOARD_MEMBER_OF_SCIENTIFIC_SOCIETIES__C
	,JJ_COUNTRY__C
	,JJ_INVOLVED_IN_GROUPS_VALUE__C
	,JJ_INVOLVED_IN_GROUPS_PRODUCING__C
	,JJ_LEADING_SPECIALIST__C
	,JJ_MANAGERIAL_ROLE_VALUE__C
	,JJ_MANAGERIAL_ROLE__C
	,JJ_RESEARCH_VALUE__C
	,JJ_RESEARCH__C
	,JJ_SPECIALITY__C
	,JJ_TREATMENT_GUIDELINES_VALUE__C
	,JJ_TREATMENT_GUIDELINES__C
	,JJ_MSL_TARGET__C
	,JJ_LAST_CONFIRMATION_DATE__C
	,JJ_STATUS_FLAG__C
	,JJ_DM_EXTERNAL_ID__C
	,JJ_SPECIALTY_NAME__C
	,JJ_ACCOUNT_COUNTRY_ISO_CODE__C
	,JJ_ACCOUNT_ELOQUA_ID__C
	,JJ_ACCOUNT_LAST_MODIFIED_DATE__C
	,JJ_ACCOUNT_MARKETING_CONTACT__C
FROM {{ source('raw', 'leading_specialist') }}