{{ config(
	post_hook="grant all privileges on {{ this }} to {{ var('snowflake_user_grant_privileges') }}")
}}

SELECT 
	COUNTRY_ISO_CODE
	,ID
	,OWNERID
	,ISDELETED
	,NAME
	,CURRENCYISOCODE
	,RECORDTYPEID
	,CREATEDDATE
	,CREATEDBYID
	,LASTMODIFIEDDATE
	,LASTMODIFIEDBYID
	,SYSTEMMODSTAMP
	,MAYEDIT
	,ISLOCKED
	,CONNECTIONRECEIVEDID
	,CONNECTIONSENTID
	,ACCOUNT_VOD__C
	,CLINICAL_TRIAL_VOD__C
	,DATE_VOD__C
	,CASE WHEN (Position(CHR(92) || CHR(92), DESCRIPTION_VOD__C) > 0) OR Position(CHR(124) || CHR(34), DESCRIPTION_VOD__C) > 0 OR Position(CHR(92) || CHR(124), DESCRIPTION_VOD__C) > 0 OR Position(CHR(92) || CHR(34), DESCRIPTION_VOD__C) > 0
		THEN REPLACE(REPLACE(REPLACE(REPLACE(DESCRIPTION_VOD__C, CHR(92) || CHR(92), CHR(92)), CHR(124) || CHR(34), CHR(34)), CHR(92) || CHR(124), CHR(124)), CHR(92) || CHR(34), CHR(34))
		ELSE DESCRIPTION_VOD__C 
	 END AS DESCRIPTION_VOD__C 
	,ENTITY_REFERENCE_ID_VOD__C
	,INTERACTION_VOD__C
	,MEDICAL_EVENT_VOD__C
	,MOBILE_ID_VOD__C
	,OTHER_SOURCE_VOD__C
	,OVERRIDE_LOCK_VOD__C
	,PUBLICATION_VOD__C
	,STATUS_VOD__C
	,CASE WHEN (Position(CHR(92) || CHR(92), SUMMARY_VOD__C) > 0) OR Position(CHR(124) || CHR(34), SUMMARY_VOD__C) > 0 OR Position(CHR(92) || CHR(124), SUMMARY_VOD__C) > 0 OR Position(CHR(92) || CHR(34), SUMMARY_VOD__C) > 0
		THEN REPLACE(REPLACE(REPLACE(REPLACE(SUMMARY_VOD__C, CHR(92) || CHR(92), CHR(92)), CHR(124) || CHR(34), CHR(34)), CHR(92) || CHR(124), CHR(124)), CHR(92) || CHR(34), CHR(34))
		ELSE SUMMARY_VOD__C 
	 END AS SUMMARY_VOD__C 
	,UNLOCK_VOD__C
	,ACCOUNT_PLAN_VOD__C
	,JJ_CUSTOMER_REQUEST__C
	,JJ_INDICATION__C
	,JJ_INSIGHTS_CATEGORY__C
	,JJ_PRODUCT__C
	,JJ_SOURCE_IN__C
	,JJ_SUBJECT__C
	,JJ_THERAPEUTIC_AREA__C
	,JJ_ACCOUNT_CLINICAL_TRIAL__C
	,JJ_ACCOUNT_PUBLICATION__C
	,JJ_SENTIMENT__C
FROM {{ source('raw', 'medical_insight') }}