{{ config(
	post_hook="grant all privileges on {{ this }} to {{ var('snowflake_user_grant_privileges') }}")
}}

with cte_aux_calls_call_planning_f_account_plan as
(
  select account_plan.id as account_plan_id,
         1 as account_plan_counter,
         account_plan.OwnerId as account_plan_owner_id,
         user_b.Name as account_plan_owner_name,
         profile_b.Name as account_plan_owner_profile_name,
         account_plan.Name as account_plan,
         left(account_plan.CreatedDate,8) as account_plan_created_date,
         left(account_plan.LastModifiedDate,8) as account_plan_last_modified_date,
         left(account_plan.JJ_Start_Date__c,8) as account_plan_start_date,
         left(account_plan.JJ_End_Date__c,8) as account_plan_end_date,
         account_plan.Account_vod__c as account_id,
         account_plan.COUNTRY_ISO_CODE as account_plan_country_code,
         country_settings.Name as account_plan_country,
         country_settings.jj_Region__c as account_plan_region,
         account_plan.Description_vod__c as account_plan_description,
         account_plan.Status__c as account_plan_status,
         case when account_plan.Active_vod__c = '1' then 'yes' else 'no' end as account_plan_is_active,
         case when (Position(CHR(92) || CHR(92), account_plan.JJ_Account_Plan_Overview__c) > 0) OR Position(CHR(124) || CHR(34), account_plan.JJ_Account_Plan_Overview__c) > 0 OR Position(CHR(92) || CHR(124), account_plan.JJ_Account_Plan_Overview__c) > 0 OR Position(CHR(92) || CHR(34), account_plan.JJ_Account_Plan_Overview__c) > 0 then REPLACE(REPLACE(REPLACE(REPLACE(account_plan.JJ_Account_Plan_Overview__c, CHR(92) || CHR(92), CHR(92)), CHR(124) || CHR(34), CHR(34)), CHR(92) || CHR(124), CHR(124)), CHR(92) || CHR(34), CHR(34)) ELSE account_plan.JJ_Account_Plan_Overview__c end as account_plan_plan_overview,
         account_plan.Percent_Complete_vod__c as account_plan_percent_complete,
         account_plan.JJ_Overall_Progress__c as account_plan_overall_progress,
         case when (Position(CHR(92) || CHR(92), account_plan.JJ_Reason_for_Deactivation__c) > 0) OR Position(CHR(124) || CHR(34), account_plan.JJ_Reason_for_Deactivation__c) > 0 OR Position(CHR(92) || CHR(124), account_plan.JJ_Reason_for_Deactivation__c) > 0 OR Position(CHR(92) || CHR(34), account_plan.JJ_Reason_for_Deactivation__c) > 0 then REPLACE(REPLACE(REPLACE(REPLACE(account_plan.JJ_Reason_for_Deactivation__c, CHR(92) || CHR(92), CHR(92)), CHR(124) || CHR(34), CHR(34)), CHR(92) || CHR(124), CHR(124)), CHR(92) || CHR(34), CHR(34)) ELSE account_plan.JJ_Reason_for_Deactivation__c end as account_plan_reason_for_deactivation,         
         account_plan.JJ_Account_Plan_Coordinator__c as account_plan_coordinator_id,
         user_coordinator.Name as account_plan_coordinator, 
         profile_coordinator.Name as account_plan_coordinator_profile_name,
         case when account_plan.JJ_Confidential__c = '1' then 'yes' else 'no' end as account_plan_is_confidential,
         account_plan.JJ_Therapeutic_Area__c as account_plan_therapeutic_area,
         case when account_plan.JJ_Umbrella_SPP__c = '1' then 'yes' else 'no' end as account_plan_is_umbrella,
         account_plan.JJ_Link_existing_SPP__c as account_plan_parent_id,
         -- IF ENVIRONMENT = UAT:
  		 'https://iconnect-emea--uat.cs9.my.salesforce.com/' || account_plan.id as account_plan_veeva_link,
  		 -- IF ENVIRONMENT = PROD:
  		 --'https://iconnect-emea.my.salesforce.com/' + account_plan.id as account_plan_veeva_link,
         substring(substring(JJ_STATUS__C, charindex('light_',JJ_STATUS__C) || len('light_'), len(JJ_STATUS__C)), 0, charindex('.gif', substring(JJ_STATUS__C, charindex('light_',JJ_STATUS__C) || len('light_'), len(JJ_STATUS__C)))) as account_plan_traffic_light_status,
         case when account_plan.JJ_STATUS__c like '%/img/samples/light_green.gif\%' then '1' else '0' end as account_plan_traffic_light_status_green_counter,
         case when account_plan.JJ_STATUS__c like '%/img/samples/light_yellow.gif\%' then '1' else '0' end as account_plan_traffic_light_status_amber_counter,
         case when account_plan.JJ_STATUS__c like '%/img/samples/light_red.gif\%' then '1' else '0' end as account_plan_traffic_light_status_red_counter,
         account_plan.JJ_KEY_ACTIONS_WITH_STATUS_AMBER__C as account_plan_key_actions_with_status_amber,
         account_plan.JJ_KEY_ACTIONS_WITH_STATUS_GREEN_COMP__C as account_plan_key_actions_with_status_green,
         account_plan.JJ_KEY_ACTIONS_WITH_STATUS_RED__C as account_plan_key_actions_with_status_red,
         case when account_plan_team_member.JJ_Account_Plan__c is not null then 'yes' else 'no' end as account_plan_has_team_members_assigned,
         case when account_plan.jj_Prioritized__c = '' then null else account_plan.jj_Prioritized__c end as account_plan_prioritized,
         case when account_plan.jj_Site_Certified__c = '' then null else account_plan.jj_Site_Certified__c end as account_plan_certified,
         left(account_plan.jj_certified_date__c,8) as account_plan_certified_date,
         account_plan.recordtypeid as account_plan_record_type,
         case when (Position(CHR(92) || CHR(92), account_plan.JJ_DRIVERS__C) > 0) OR Position(CHR(124) || CHR(34), account_plan.JJ_DRIVERS__C) > 0 OR Position(CHR(92) || CHR(124), account_plan.JJ_DRIVERS__C) > 0 OR Position(CHR(92) || CHR(34), account_plan.JJ_DRIVERS__C) > 0 then REPLACE(REPLACE(REPLACE(REPLACE(account_plan.JJ_DRIVERS__C, CHR(92) || CHR(92), CHR(92)), CHR(124) || CHR(34), CHR(34)), CHR(92) || CHR(124), CHR(124)), CHR(92) || CHR(34), CHR(34)) ELSE account_plan.JJ_DRIVERS__C end as account_plan_drivers,         
         case when (Position(CHR(92) || CHR(92), account_plan.JJ_BARRIERS__C) > 0) OR Position(CHR(124) || CHR(34), account_plan.JJ_BARRIERS__C) > 0 OR Position(CHR(92) || CHR(124), account_plan.JJ_BARRIERS__C) > 0 OR Position(CHR(92) || CHR(34), account_plan.JJ_BARRIERS__C) > 0 then REPLACE(REPLACE(REPLACE(REPLACE(account_plan.JJ_BARRIERS__C, CHR(92) || CHR(92), CHR(92)), CHR(124) || CHR(34), CHR(34)), CHR(92) || CHR(124), CHR(124)), CHR(92) || CHR(34), CHR(34)) ELSE account_plan.JJ_BARRIERS__C end as account_plan_barriers
    from      {{ var('schema') }}.account_plan_raw            as account_plan
    left join {{ var('schema') }}.user_raw                           as user_b
      on account_plan.OwnerId                                               = user_b.Id
    left join {{ var('schema') }}.profile_raw                        as profile_b
      on profile_b.Id                                                       = user_b.profileId 
     and account_plan.OwnerId                                               = user_b.Id
    left join {{ var('schema') }}.country_settings_raw         as country_settings
      on account_plan.COUNTRY_ISO_CODE                                      = country_settings.jj_Country_ISO_Code__c
    left join {{ var('schema') }}.user_raw                           as user_coordinator
      on account_plan.JJ_Account_Plan_Coordinator__c                        = user_coordinator.Id
    left join {{ var('schema') }}.profile_raw                        as profile_coordinator
      on profile_coordinator.Id                                             = user_coordinator.profileId  
    left join {{ var('schema') }}.account_plan_team_member_raw as account_plan_team_member
      on account_plan_team_member.JJ_Account_Plan__c                        = account_plan.id  
   group by account_plan_id,
            account_plan_counter,
            account_plan_owner_id,
            account_plan_owner_name,
            account_plan_owner_profile_name,
            account_plan,
            account_plan_created_date,
            account_plan_last_modified_date,
            account_plan_start_date,
            account_plan_end_date,
            account_id,
            account_plan_country_code,
            account_plan_country,
            account_plan_region,
            account_plan_description,
            account_plan_status,
            account_plan_is_active,
            account_plan_plan_overview,
            account_plan_percent_complete,
            account_plan_overall_progress,
            account_plan_reason_for_deactivation,
            account_plan_coordinator_id,
            account_plan_coordinator, 
            account_plan_coordinator_profile_name,
            account_plan_is_confidential,
            account_plan_therapeutic_area,
            account_plan_is_umbrella,
            account_plan_parent_id,
            account_plan_veeva_link,
            account_plan_traffic_light_status,
            account_plan_traffic_light_status_green_counter,
            account_plan_traffic_light_status_amber_counter,
            account_plan_traffic_light_status_red_counter,
            account_plan_key_actions_with_status_amber,
            account_plan_key_actions_with_status_green,
            account_plan_key_actions_with_status_red,
            account_plan_has_team_members_assigned,
            account_plan_prioritized,
            account_plan_certified,
            account_plan_certified_date,
            account_plan_record_type,
            account_plan_drivers,        
            account_plan_barriers		  
)
select account_plan_id::varchar(50)                                as account_plan_id,
       account_plan_counter::varchar(1)                            as account_plan_counter,
       account_plan_owner_id::varchar(50)                          as account_plan_owner_id,
       account_plan_owner_name::varchar(256)                       as account_plan_owner_name,
       account_plan_owner_profile_name::varchar(256)               as account_plan_owner_profile_name,
       account_plan::varchar(256)                                  as account_plan,
       account_plan_created_date::varchar(8)                       as account_plan_created_date,
       account_plan_last_modified_date::varchar(8)                 as account_plan_last_modified_date,
       account_plan_start_date::varchar(8)                         as account_plan_start_date,
       account_plan_end_date::varchar(8)                           as account_plan_end_date,
       account_id::varchar(50)                                     as account_id,
       account_plan_country_code::varchar(100)                     as account_plan_country_code,
       account_plan_country::varchar(50)                           as account_plan_country,
       account_plan_region::varchar(50)                            as account_plan_region,
       account_plan_description::varchar(510)                      as account_plan_description,
       account_plan_status::varchar(510)                           as account_plan_status,
       account_plan_is_active::varchar(10)                         as account_plan_is_active,
       account_plan_plan_overview::varchar(2600)                   as account_plan_plan_overview,
       account_plan_percent_complete::varchar(10)                  as account_plan_percent_complete,
       account_plan_overall_progress::varchar(10)                  as account_plan_overall_progress,
       account_plan_reason_for_deactivation::varchar(510)          as account_plan_reason_for_deactivation,
       account_plan_coordinator_id::varchar(50)                    as account_plan_coordinator_id,
       account_plan_coordinator:: varchar(256)                      as account_plan_coordinator,
       account_plan_coordinator_profile_name::varchar(256)         as account_plan_coordinator_profile_name,
       account_plan_is_confidential::varchar(10)                   as account_plan_is_confidential,
       account_plan_therapeutic_area::varchar(510)                 as account_plan_therapeutic_area,
       account_plan_is_umbrella::varchar(10)                       as account_plan_is_umbrella,
       account_plan_parent_id::varchar(50)                         as account_plan_parent_id,
       account_plan_veeva_link::varchar(256)                       as account_plan_veeva_link,
       account_plan_traffic_light_status::varchar(50)              as account_plan_traffic_light_status,
       account_plan_traffic_light_status_green_counter::varchar(1) as account_plan_traffic_light_status_green_counter,
       account_plan_traffic_light_status_amber_counter::varchar(1) as account_plan_traffic_light_status_amber_counter,
       account_plan_traffic_light_status_red_counter::varchar(1)   as account_plan_traffic_light_status_red_counter,
       account_plan_key_actions_with_status_amber::varchar(13)     as account_plan_key_actions_with_status_amber,
       account_plan_key_actions_with_status_green::varchar(13)     as account_plan_key_actions_with_status_green,
       account_plan_key_actions_with_status_red::varchar(13)       as account_plan_key_actions_with_status_red,
       account_plan_has_team_members_assigned::varchar(10)         as account_plan_has_team_members_assigned,
	   account_plan_prioritized::integer                           as account_plan_prioritized,
       account_plan_certified::integer                             as account_plan_certified,
       account_plan_certified_date::varchar(8)                     as account_plan_certified_date,
       account_plan_record_type::varchar(36)                       as account_plan_record_type,
       account_plan_drivers::varchar(10000)                        as account_plan_drivers,
       account_plan_barriers::varchar(10000)                       as account_plan_barriers
  from cte_aux_calls_call_planning_f_account_plan