{{ config(
	post_hook="grant all privileges on {{ this }} to {{ var('snowflake_user_grant_privileges') }}")
}}

select action__c::varchar(200) as action,
       action_detail__c::varchar(510) as action_detail,
       connectionreceivedid::varchar(36) as connection_received_id,
       connectionsentid::varchar(36) as connection_sent_id,
       createdbyid::varchar(36) as created_by_id,
       case when createddate = '' then null else TO_TIMESTAMP(createddate,'YYYYMMDD HH24:MI:SS') end::datetime as created_date,
       currencyisocode::varchar(6) as currency_iso_code,
       case when date__c = '' then null else TO_TIMESTAMP(date__c,'YYYYMMDD HH24:MI:SS') end::datetime as date,
       device__c::varchar(200) as device,
       html_report__c::varchar(36) as html_report_id,
       html_report_name__c::varchar(2600) as html_report_name,
       id::varchar(36) as myinsights_analytics_id,
       case when islocked = '' then null else islocked end::integer as is_locked,
       case when isonline__c = '' then null else isonline__c end::integer as is_online,
       jj_account_id__c::varchar(510) as account_id,
       jj_brand_indicator__c::varchar(510) as brand_indicator,
       jj_channel__c::varchar(510) as channel,
       jj_cods_id__c::varchar(510) as cods_id,
       jj_content_recommendation__c::varchar(510) as content_recommendation,
       jj_country__c::varchar(510) as country,
       jj_dashboard_name__c::varchar(510) as dashboard_name,
       case when jj_date_time__c = '' then null else cast(jj_date_time__c as datetime) end::datetime as date_time,
       jj_event__c::varchar(510) as event,
       jj_event_sub_type__c::varchar(510) as event_sub_type,
       case when jj_expiry_date__c = '' then null else cast(jj_expiry_date__c as datetime) end::datetime as expiry_date,
       jj_favourite_product__c::varchar(510) as favourite_product,
       jj_feedback__c::varchar(510) as feedback,
       jj_filter_field__c::varchar(510) as filter_field,
       jj_filter_value__c::varchar(510) as filter_value,
       jj_linked_object_name__c::varchar(510) as linked_object_name,
       jj_linked_object_record_id__c::varchar(510) as linked_object_record_id,
       jj_product__c::varchar(510) as product,
       jj_profile__c::varchar(510) as profile,
       jj_reasoning__c::varchar(510) as reasoning,
       jj_report_id__c::varchar(510) as report_id,
       jj_role__c::varchar(510) as role,
       jj_sales_line__c::varchar(510) as sales_line,
       jj_segment__c::varchar(510) as segment,
       jj_session_id__c::varchar(510) as session_id,
       jj_sort_field__c::varchar(510) as sort_field,
       jj_tab_name__c::varchar(510) as tab_name,
       jj_territory__c::varchar(510) as territory,
       jj_user_id__c::varchar(510) as user_id,
       case when lastactivitydate = '' then null else cast(lastactivitydate as datetime) end::datetime as last_activity_date,
       lastmodifiedbyid::varchar(36) as last_modified_by_id,
       case when lastmodifieddate = '' then null else TO_TIMESTAMP(lastmodifieddate,'YYYYMMDD HH24:MI:SS') end::datetime as last_modified_date,
       case when mayedit = '' then null else mayedit end::integer as may_edit,
       mobile_id_vod__c::varchar(200) as mobile_id,
       name::varchar(160) as name,
       ownerid::varchar(36) as owner_id,
       case when systemmodstamp = '' then null else TO_TIMESTAMP(systemmodstamp,'YYYYMMDD HH24:MI:SS') end::datetime as system_mod_stamp,
       user__c::varchar(36) as employee_id,
       user_country__c::varchar(2600) as user_country,
       user_feedback__c::varchar(10000) as user_feedback,
       user_profile__c::varchar(2600) as user_profile
  from {{ var('schema') }}.myinsights_analytics_raw