{{ config(
	post_hook="grant all privileges on {{ this }} to {{ var('snowflake_user_grant_privileges') }}")
}}

SELECT  
	 COUNTRY_ISO_CODE
	,ID
	,OWNERID
	,ISDELETED
	,NAME
	,CURRENCYISOCODE
	,CREATEDDATE
	,CREATEDBYID
	,LASTMODIFIEDDATE
	,LASTMODIFIEDBYID
	,SYSTEMMODSTAMP
	,MAYEDIT
	,ISLOCKED
	,CONNECTIONRECEIVEDID
	,CONNECTIONSENTID
	,JJ_ELQ_ACTIVITYID__C AS ACTIVITYID
	,JJ_ELQ_ACTIVITY_DATE__C AS ACTIVITY_DATE
	,JJ_ELQ_ACTIVITY_TYPE__C AS ACTIVITY_TYPE
	,JJ_ELQ_ASSETID__C AS ASSETID
	,JJ_ELQ_ASSETTYPE__C AS ASSETTYPE
	,JJ_ELQ_ASSET_NAME__C AS ASSET_NAME
	,JJ_ELQ_CAMPAIGN_ID__C AS CAMPAIGN_ID
	,JJ_ELQ_CONTACTCODSID__C AS CONTACTCODSID
	,JJ_ELQ_CONTACT_ELOQUA_ID__C AS CONTACT_ELOQUA_ID
	,JJ_ELQ_CONTACT_EMAIL_ADDRESS__C AS CONTACT_EMAIL_ADDRESS
	,JJ_ELQ_CONTACT_ID__C AS CONTACT_ID
	,JJ_ELQ_DURATION__C AS DURATION
	,JJ_ELQ_EMAILDEPLOYMENTID__C AS EMAILDEPLOYMENTID
	,JJ_ELQ_EMAILRECIPIENTID__C AS EMAILRECIPIENTID
	,JJ_ELQ_ERROR_MESSAGE__C AS ERROR_MESSAGE
	,JJ_ELQ_EXTERNALID__C AS EXTERNALID
	,JJ_ELQ_FIRSTPAGEVIEWURL__C AS FIRSTPAGEVIEWURL
	,JJ_ELQ_LINK__C AS LINK
	,JJ_ELQ_NUMBEROFPAGES__C AS NUMBEROFPAGES
	,JJ_ELQ_SMTPERRORCODE__C AS SMTPERRORCODE
	,CASE WHEN Position(CHR(124) || CHR(34), JJ_ELQ_SMTPMESSAGE__C) > 0 THEN TRANSLATE(JJ_ELQ_SMTPMESSAGE__C, CHR(124) || CHR(34), CHR(34))
		WHEN Position(CHR(92) || CHR(124), JJ_ELQ_SMTPMESSAGE__C) > 0 THEN TRANSLATE(JJ_ELQ_SMTPMESSAGE__C, CHR(92) || CHR(124), CHR(124))
		WHEN Position(CHR(92) || CHR(34), JJ_ELQ_SMTPMESSAGE__C) > 0 THEN TRANSLATE(JJ_ELQ_SMTPMESSAGE__C, CHR(92) || CHR(34), CHR(34))
		ELSE JJ_ELQ_SMTPMESSAGE__C END AS SMTPMESSAGE
	,JJ_ELQ_SMTPSTATUSCODE__C AS SMTPSTATUSCODE
	,JJ_ELQ_SOURCE_SYSTEM__C AS SOURCE_SYSTEM
	,JJ_ELQ_STATUS__C AS STATUS
	,CASE WHEN Position(CHR(124) || CHR(34), JJ_ELQ_SUBJECTLINE__C) > 0 THEN TRANSLATE(JJ_ELQ_SUBJECTLINE__C, CHR(124) || CHR(34), CHR(34))
		WHEN Position(CHR(92) || CHR(124), JJ_ELQ_SUBJECTLINE__C) > 0 THEN TRANSLATE(JJ_ELQ_SUBJECTLINE__C, CHR(92) || CHR(124), CHR(124))
		WHEN Position(CHR(92) || CHR(34), JJ_ELQ_SUBJECTLINE__C) > 0 THEN TRANSLATE(JJ_ELQ_SUBJECTLINE__C, CHR(92) || CHR(34), CHR(34))
		ELSE JJ_ELQ_SUBJECTLINE__C END AS SUBJECTLINE
	,CASE WHEN Position(CHR(124) || CHR(34), JJ_ELQ_URL__C) > 0 THEN TRANSLATE(JJ_ELQ_URL__C, CHR(124) || CHR(34), CHR(34))
		WHEN Position(CHR(92) || CHR(124), JJ_ELQ_URL__C) > 0 THEN TRANSLATE(JJ_ELQ_URL__C, CHR(92) || CHR(124), CHR(124))
		WHEN Position(CHR(92) || CHR(34), JJ_ELQ_URL__C) > 0 THEN TRANSLATE(JJ_ELQ_URL__C, CHR(92) || CHR(34), CHR(34))
		ELSE JJ_ELQ_URL__C END AS URL			
	,JJ_ELQ_WEBVISITID__C AS WEBVISITID
FROM {{ var('schema') }}.elq_activity_raw