{{ config(
	post_hook="grant all privileges on {{ this }} to {{ var('snowflake_user_grant_privileges') }}")
}}

SELECT 
	ID
	,OWNERID
	,NAME
	,CURRENCYISOCODE
	,RECORDTYPEID
	,CREATEDDATE
	,CREATEDBYID
	,LASTMODIFIEDDATE
	,LASTMODIFIEDBYID
	,ACCOUNT_VOD__C
	,CLINICAL_TRIALS_FOCUS_SCORE_VOD__C
	,EVENTS_FOCUS_SCORE_VOD__C
	,EXTERNAL_ID_VOD__C
	,FOCUS_AREA_ACCOUNT_VOD__C
	,FOCUS_NAME_VOD__C
	,HIGH_FOCUS_SCORE_VOD__C
	,PUBLICATIONS_FOCUS_SCORE_VOD__C
	,TOTAL_FOCUS_SCORE_VOD__C
	,RECORD_TYPE_NAME_VOD__C
	,JJ_COMPLETED_TRIALS__C
	,JJ_DISEASE_AREA__C
	,JJ_EXPERT_SCORE__C
	,JJ_FIRST_AUTHOR_PUBLICATIONS__C
	,JJ_FIRST_PUBLICATION_YEAR__C
	,JJ_JANSSEN_PRINCIPAL_INVESTIGATOR__C
	,JJ_JANSSEN_TRIALS__C
	,JJ_LAST_PUBLICATION_YEAR__C
	,JJ_MODIFIED__C
	,JJ_NUMBER_OF_CITATIONS__C
	,JJ_NUMBER_OF_PUBLICATIONS__C
	,JJ_ONGOING_TRIALS__C
	,JJ_SENIOR_AUTHOR_PUBLICATIONS__C
	,JJ_SITE_TROVE_TIER__C
	,JJ_THERAPEUTIC_AREA__C
	,JJ_CT_FOCUS_SCORE__C
	,JJ_JP_INVESTIGATOR__C
FROM {{ var('schema') }}.focus_area_raw