{{ config(
	post_hook="grant all privileges on {{ this }} to {{ var('snowflake_user_grant_privileges') }}")
}}

select country_iso_code
     , id
     , recordtypeid
     , whoid
     , whatid
     , subject
     , activitydate
     , status
     , priority
     , ishighpriority
     , ownerid
     , description
     , currencyisocode
     , type
     , isdeleted
     , accountid
     , isclosed
     , createddate
     , createdbyid
     , lastmodifieddate
     , lastmodifiedbyid
     , systemmodstamp
     , isarchived
     , isvisibleinselfservice
     , calldurationinseconds
     , calltype
     , calldisposition
     , callobject
     , reminderdatetime
     , isreminderset
     , connectionreceivedid
     , connectionsentid
     , recurrenceactivityid
     , isrecurrence
     , recurrencestartdateonly
     , recurrenceenddateonly
     , recurrencetimezonesidkey
     , recurrencetype
     , recurrenceinterval
     , recurrencedayofweekmask
     , recurrencedayofmonth
     , recurrenceinstance
     , recurrencemonthofyear
     , recurrenceregeneratedtype
     , tasksubtype
     , override_lock_vod__c
     , mobile_id_vod__c
     , color_vod__c
     , campaign__c
     , date_time_opened__c
     , date_time_sent__c
     , from_name__c
     , ier_id__c
     , followup_activity_type_vod__c
     , number_of_total_clicks__c
     , opened__c
     , jj_medical__c
     , jj_percentage__c
     , jj_response_type__c
     , call_campaign_name__c
     , interaction_id__c
     , jj_system_campaign_id__c
     , nvmcontactworld__acd__c
     , nvmcontactworld__cw_call_end_time__c
     , nvmcontactworld__cw_call_start_time__c
     , nvmcontactworld__contactworld_number__c
     , nvmcontactworld__customer_number__c
     , nvmcontactworld__service_name__c
     , jj_activity_date_time__c
     , jj_asset_name__c
     , jj_click_through_link__c
     , jj_click_through_url__c
     , event_canceled_vod__c
     , jj_campaign_step_id__c
     , jj_mtg_duedate__c
     , jj_mtg_productphaseactivityduedate__c
     , nvmcontactworld__callringtimeinseconds__c
     , nvmcontactworld__calltalktimeinseconds__c
     , nvmcontactworld__interactionquality__c
     , nvmcontactworld__was_call_recorded__c
  from {{ var('schema') }}.task_raw aux2
 where LOWER(type) = 'email'
 group by country_iso_code
        , id
        , recordtypeid
        , whoid
        , whatid
        , subject
        , activitydate
        , status
        , priority
        , ishighpriority
        , ownerid
        , description
        , currencyisocode
        , type
        , isdeleted
        , accountid
        , isclosed
        , createddate
        , createdbyid
        , lastmodifieddate
        , lastmodifiedbyid
        , systemmodstamp
        , isarchived
        , isvisibleinselfservice
        , calldurationinseconds
        , calltype
        , calldisposition
        , callobject
        , reminderdatetime
        , isreminderset
        , connectionreceivedid
        , connectionsentid
        , recurrenceactivityid
        , isrecurrence
        , recurrencestartdateonly
        , recurrenceenddateonly
        , recurrencetimezonesidkey
        , recurrencetype
        , recurrenceinterval
        , recurrencedayofweekmask
        , recurrencedayofmonth
        , recurrenceinstance
        , recurrencemonthofyear
        , recurrenceregeneratedtype
        , tasksubtype
        , override_lock_vod__c
        , mobile_id_vod__c
        , color_vod__c
        , campaign__c
        , date_time_opened__c
        , date_time_sent__c
        , from_name__c
        , ier_id__c
        , followup_activity_type_vod__c
        , number_of_total_clicks__c
        , opened__c
        , jj_medical__c
        , jj_percentage__c
        , jj_response_type__c
        , call_campaign_name__c
        , interaction_id__c
        , jj_system_campaign_id__c
        , nvmcontactworld__acd__c
        , nvmcontactworld__cw_call_end_time__c
        , nvmcontactworld__cw_call_start_time__c
        , nvmcontactworld__contactworld_number__c
        , nvmcontactworld__customer_number__c
        , nvmcontactworld__service_name__c
        , jj_activity_date_time__c
        , jj_asset_name__c
        , jj_click_through_link__c
        , jj_click_through_url__c
        , event_canceled_vod__c
        , jj_campaign_step_id__c
        , jj_mtg_duedate__c
        , jj_mtg_productphaseactivityduedate__c
        , nvmcontactworld__callringtimeinseconds__c
        , nvmcontactworld__calltalktimeinseconds__c
        , nvmcontactworld__interactionquality__c
        , nvmcontactworld__was_call_recorded__c

 union

select country_iso_code
     , 'EmailOpen' || ((Random()*100000)::varchar(255)) AS id
     , recordtypeid
     , whoid
     , whatid
     , subject
     , activitydate
     , status
     , priority
     , ishighpriority
     , ownerid
     , description
     , currencyisocode
     , type
     , isdeleted
     , accountid
     , isclosed
     , createddate
     , createdbyid
     , lastmodifieddate
     , lastmodifiedbyid
     , systemmodstamp
     , isarchived
     , isvisibleinselfservice
     , calldurationinseconds
     , calltype
     , calldisposition
     , callobject
     , reminderdatetime
     , isreminderset
     , connectionreceivedid
     , connectionsentid
     , recurrenceactivityid
     , isrecurrence
     , recurrencestartdateonly
     , recurrenceenddateonly
     , recurrencetimezonesidkey
     , recurrencetype
     , recurrenceinterval
     , recurrencedayofweekmask
     , recurrencedayofmonth
     , recurrenceinstance
     , recurrencemonthofyear
     , recurrenceregeneratedtype
     , tasksubtype
     , override_lock_vod__c
     , mobile_id_vod__c
     , color_vod__c
     , campaign__c
     , date_time_opened__c
     , date_time_sent__c
     , from_name__c
     , ier_id__c
     , followup_activity_type_vod__c
     , number_of_total_clicks__c
     , opened__c
     , jj_medical__c
     , jj_percentage__c
     , 'Email Opened'::varchar(255) AS jj_response_type__c
     , call_campaign_name__c
     , interaction_id__c
     , jj_system_campaign_id__c
     , nvmcontactworld__acd__c
     , nvmcontactworld__cw_call_end_time__c
     , nvmcontactworld__cw_call_start_time__c
     , nvmcontactworld__contactworld_number__c
     , nvmcontactworld__customer_number__c
     , nvmcontactworld__service_name__c
     , jj_activity_date_time__c
     , jj_asset_name__c
     , jj_click_through_link__c
     , jj_click_through_url__c
     , event_canceled_vod__c
     , jj_campaign_step_id__c
     , jj_mtg_duedate__c
     , jj_mtg_productphaseactivityduedate__c
     , nvmcontactworld__callringtimeinseconds__c
     , nvmcontactworld__calltalktimeinseconds__c
     , nvmcontactworld__interactionquality__c
     , nvmcontactworld__was_call_recorded__c
  from {{ var('schema') }}.task_raw
 where LOWER(type) = 'email' 
   and LOWER(jj_response_type__c) = 'clickthrough'
   and (trim(subject) || '-' || accountid || '-' || ownerid) not in (
                                                                  select trim(subject) || '-' || accountid || '-' || ownerid
                                                                    from {{ var('schema') }}.task_raw
                                                                   where LOWER(jj_Response_Type__c) = 'email opened'
                                                                )
 group by country_iso_code
        , 'EmailOpen' || ((Random()*100000)::varchar(255))
        , recordtypeid
        , whoid
        , whatid
        , subject
        , activitydate
        , status
        , priority
        , ishighpriority
        , ownerid
        , description
        , currencyisocode
        , type
        , isdeleted
        , accountid
        , isclosed
        , createddate
        , createdbyid
        , lastmodifieddate
        , lastmodifiedbyid
        , systemmodstamp
        , isarchived
        , isvisibleinselfservice
        , calldurationinseconds
        , calltype
        , calldisposition
        , callobject
        , reminderdatetime
        , isreminderset
        , connectionreceivedid
        , connectionsentid
        , recurrenceactivityid
        , isrecurrence
        , recurrencestartdateonly
        , recurrenceenddateonly
        , recurrencetimezonesidkey
        , recurrencetype
        , recurrenceinterval
        , recurrencedayofweekmask
        , recurrencedayofmonth
        , recurrenceinstance
        , recurrencemonthofyear
        , recurrenceregeneratedtype
        , tasksubtype
        , override_lock_vod__c
        , mobile_id_vod__c
        , color_vod__c
        , campaign__c
        , date_time_opened__c
        , date_time_sent__c
        , from_name__c
        , ier_id__c
        , followup_activity_type_vod__c
        , number_of_total_clicks__c
        , opened__c
        , jj_medical__c
        , jj_percentage__c
        , 'Email Opened'::varchar(255)
        , call_campaign_name__c
        , interaction_id__c
        , jj_system_campaign_id__c
        , nvmcontactworld__acd__c
        , nvmcontactworld__cw_call_end_time__c
        , nvmcontactworld__cw_call_start_time__c
        , nvmcontactworld__contactworld_number__c
        , nvmcontactworld__customer_number__c
        , nvmcontactworld__service_name__c
        , jj_activity_date_time__c
        , jj_asset_name__c
        , jj_click_through_link__c
        , jj_click_through_url__c
        , event_canceled_vod__c
        , jj_campaign_step_id__c
        , jj_mtg_duedate__c
        , jj_mtg_productphaseactivityduedate__c
        , nvmcontactworld__callringtimeinseconds__c
        , nvmcontactworld__calltalktimeinseconds__c
        , nvmcontactworld__interactionquality__c
        , nvmcontactworld__was_call_recorded__c